// This file is automatically generated by the Firebase-Studio.
// Do not edit this file manually, as your changes will be overwritten.

'use client';

import { onAuthStateChanged, User } from 'firebase/auth';
import { useEffect, useState } from 'react';
import { useAuth } from '../provider';

/**
 * A hook to get the current user.
 * This hook is used to get the current user from Firebase Auth.
 * It will return the user object if the user is logged in, null if the user is logged out, and undefined if the user state is still loading.
 * @returns The current user, null if logged out, or undefined if loading.
 */
export function useUser() {
  const auth = useAuth();
  const [user, setUser] = useState<User | null | undefined>(undefined);

  useEffect(() => {
    const unsubscribe = onAuthStateChanged(auth, (user) => {
      setUser(user);
    });

    return () => unsubscribe();
  }, [auth]);

  return user;
}
