// This file is automatically generated by the Firebase-Studio.
// Do not edit this file manually, as your changes will be overwritten.

'use client';

import {
  collection,
  onSnapshot,
  query,
  where,
  type DocumentData,
  type Firestore,
  type Query,
} from 'firebase/firestore';
import { useEffect, useState }from 'react';

import { useFirestore } from '../provider';

/**
 * A hook to get a collection from Firestore.
 * This hook is used to get a collection from Firestore and listen for updates.
 * It will return the collection data, loading state, and error state.
 * @param path The path to the collection.
 * @param queryConstraints The query constraints to apply to the collection.
 * @returns The collection data, loading state, and error state.
 */
export function useCollection<T = DocumentData>(
  path: string,
  queryConstraints: any[] = []
) {
  const firestore = useFirestore();
  const [data, setData] = useState<T[] | undefined>(undefined);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<Error | undefined>(undefined);

  useEffect(() => {
    const collectionRef = collection(firestore, path);
    const q = query(collectionRef, ...queryConstraints.map(constraint => where(constraint.field, constraint.operator, constraint.value)));

    const unsubscribe = onSnapshot(
      q,
      (snapshot) => {
        const docs = snapshot.docs.map((doc) => ({
          ...doc.data(),
          id: doc.id,
        })) as T[];
        setData(docs);
        setLoading(false);
      },
      (err) => {
        setError(err);
        setLoading(false);
      }
    );

    return () => unsubscribe();
  }, [firestore, path, JSON.stringify(queryConstraints)]);

  return { data, loading, error };
}
