// This file is automatically generated by the Firebase-Studio.
// Do not edit this file manually, as your changes will be overwritten.

/**
 * The Firebase project configuration object.
 * This is used to initialize the Firebase app.
 * It is safe to expose this to the client.
 */
export const firebaseConfig = {
  apiKey: "placeholder",
  authDomain: "placeholder",
  projectId: "placeholder",
  storageBucket: "placeholder",
  messagingSenderId: "placeholder",
  appId: "placeholder"
};
