// This file is automatically generated by the Firebase-Studio.
// Do not edit this file manually, as your changes will be overwritten.

'use client';

import { createContext, useContext, ReactNode } from 'react';
import { FirebaseApp } from 'firebase/app';
import { Auth } from 'firebase/auth';
import { Firestore } from 'firebase/firestore';
import { initializeFirebase } from '.';

/**
 * The context for the Firebase app.
 * This is used to provide the Firebase app to all components.
 */
const FirebaseContext = createContext<
  | {
      app: FirebaseApp;
      auth: Auth;
      firestore: Firestore;
    }
  | undefined
>(undefined);

/**
 * A provider for the Firebase app.
 * This should be used to wrap the root of the application.
 * @param children The children to render.
 * @param app The Firebase app.
 * @param auth The Firebase auth instance.
 * @param firestore The Firebase firestore instance.
 */
export function FirebaseProvider({
  children,
  app,
  auth,
  firestore,
}: {
  children: ReactNode;
  app: FirebaseApp;
  auth: Auth;
  firestore: Firestore;
}) {
  return (
    <FirebaseContext.Provider value={{ app, auth, firestore }}>
      {children}
    </FirebaseContext.Provider>
  );
}

/**
 * A hook to get the Firebase context.
 * This should be used to get the Firebase app, auth, and firestore instances.
 * @returns The Firebase context.
 */
export function useFirebase() {
  const context = useContext(FirebaseContext);
  if (context === undefined) {
    throw new Error('useFirebase must be used within a FirebaseProvider');
  }
  return context;
}

/**
 * A hook to get the Firebase app.
 * This should be used to get the Firebase app instance.
 * @returns The Firebase app instance.
 */
export function useFirebaseApp() {
  return useFirebase().app;
}

/**
 * A hook to get the Firebase auth instance.
 * This should be used to get the Firebase auth instance.
 * @returns The Firebase auth instance.
 */
export function useAuth() {
  return useFirebase().auth;
}

/**
 * A hook to get the Firebase firestore instance.
 * This should be used to get the Firebase firestore instance.
 * @returns The Firebase firestore instance.
 */
export function useFirestore() {
  return useFirebase().firestore;
}

/**
 * A client provider for the Firebase app.
 * This should be used to wrap the root of the application on the client.
 * @param children The children to render.
 */
export function FirebaseClientProvider({ children }: { children: ReactNode }) {
  const { app, auth, firestore } = initializeFirebase();
  return (
    <FirebaseProvider app={app} auth={auth} firestore={firestore}>
      {children}
    </FirebaseProvider>
  );
}
